# Generated by Django 5.0.3 on 2024-04-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='achivement',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='diary',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='answer',
            field=models.TextField(),
        ),
    ]
