# Generated by Django 5.0.3 on 2024-05-26 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0006_remove_member_is_public_memberinfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="requirement",
        ),
    ]
