# Generated by Django 5.0.3 on 2024-05-26 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0008_remove_collection_end_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="achivement",
            new_name="achievement",
        ),
    ]
